apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: us.gcr.io/directed-relic-285313/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/directed-relic-285313/tickets
      context: tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/directed-relic-285313/orders
    - image: us.gcr.io/directed-relic-285313/expiration
      context: expiration
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: us.gcr.io/directed-relic-285313/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: directed-relic-285313
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
