apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-pod
  template:
    metadata:
      labels:
        app: expiration-pod
    spec:
      containers:
        - name: expiration-container
          image: us.gcr.io/directed-relic-285313/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-service
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
