apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-pod
  template:
    metadata:
      labels:
        app: tickets-pod
    spec:
      containers:
        - name: tickets-container
          image: us.gcr.io/directed-relic-285313/tickets
          env:
            - name: JWT_KEY #name of env variable as it shows up inside container
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: MONGO_URI
              value: "mongodb://tickets-mongo-service:27017/tickets"
            - name: NATS_URL
              value: "http://nats-service:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  type: ClusterIP
  selector:
    app: tickets-pod
  ports:
    - name: tickets-port
      protocol: TCP
      port: 3000
      targetPort: 3000
